[colors]
surface_global      = "#0a0a0d"
surface_active      = "#19191c"
surface_inactive    = "#0a0a0d"
surface_error       = "#e03e3e"

text_primary        = "#d2d2d7"
text_secondary      = "#ff4646"
text_secondary_in   = "#a62e2e"
text_selection      = "#0a0a0d"
text_muted          = "#646468"

border_active       = "#dcdc64"
border_inactive     = "#0a0a0d"

selection           = "#dcdc64"
selection_inactive  = "#82823C"

accent              = "#dcdc64"
accent_inactive     = "#82823C"

progress            = [ "#444446", 
                        "#ff4646", 
                        "#d2d2d7" ]

progress_speed      = 2

[borders]
border_display      = "all"
border_type         = "rounded"

[extras]
is_dark             = true
decorator           = "â˜†"

