[colors]
surface_global      = "#272822"
surface_active      = "#3E3D32"
surface_inactive    = "#2C2B26"
surface_error       = "#F92672"

text_primary        = "#F8F8F2"
text_secondary      = "#FD971F"
text_secondary_in   = "#C57B13"
text_selection      = "#272822"
text_muted          = "#95917E"

border_active       = "#A6E22E"
border_inactive     = "#49483E"

selection           = "#A6E22E"
selection_inactive  = "#75715E"

accent              = "#FD971F"
accent_inactive     = "#C57B13"

[borders]
border_display      = "all"
border_type         = "rounded"

[progress]            
elapsed              = [ "#F8F8F2",
                        "#FD971F",
                        "#C57B13" ]

unplayed            = "still"

waveform_style      = "block8"
oscilloscope_style  = "blocky"

[extras]
decorator           = "Û∞ìè"

